AWSTemplateFormatVersion: '2010-09-09'
Description: 'This is a Sample template for creating a ecr'

Parameters:
  Environment:
    Description: The environment of this ECR instance
    Type: String
    AllowedValues: [np-dev,np-stage,prod]
  AppName:
    Description: The name the application where this ECR belongs to
    Type: String
  ImageTagMutability:
    Description: The tag mutability setting for the repo
    Type: String
    AllowedValues: [IMMUTABLE,MUTABLE]
    Default: MUTABLE
  Service:
    Description: The name of the service this ECR repo is for e.g. ui / engine ...etc
    Type: String  
Resources:
  ECR: 
    Type: AWS::ECR::Repository
    Properties: 
      RepositoryName: !Sub "${Environment}-${AppName}-${Service}"
      ImageScanningConfiguration: 
        scanOnPush: "true"
      Tags:
        - Key: env
          Value: !Ref Environment
        - Key: app
          Value: !Ref AppName
Outputs:
  ECRName:
    Description: The Name of the ECR created
    Value: !Ref ECR
  ECRArn:
    Description: The arn of the ECR created
    Value: !GetAtt ECR.Arn